// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TreasuryApp.API.Persistence.Contexts;

namespace TreasuryApp.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200518230941_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TreasuryApp.API.Domain.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EODGLDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastEODDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MRSName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<DateTime>("NextEODDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextTradingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParentEntity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhysicalAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportingCurrency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuspenseGLAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SwiftAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TradingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            Country = "Nigeria",
                            EODGLDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(8149),
                            LastEODDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(7088),
                            MRSName = "FF",
                            Name = "Beta Highdeas InfoTech",
                            NextEODDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(7617),
                            NextTradingDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(6465),
                            ParentEntity = "XXX",
                            PhoneNumber = "08030721539",
                            PhysicalAddress = "57 Marina Rd, Lagos, ",
                            ReportingCurrency = "USD",
                            ShortName = "BetaHitech",
                            SuspenseGLAccount = "900USD100000",
                            SwiftAddress = "XXXYYYZZZ",
                            TradingDate = new DateTime(2020, 5, 19, 0, 9, 40, 844, DateTimeKind.Local).AddTicks(2857)
                        },
                        new
                        {
                            Id = 101,
                            Country = "Nigeria",
                            EODGLDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(9274),
                            LastEODDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(9263),
                            MRSName = "QQ",
                            Name = "Bisi and Sons Ltd",
                            NextEODDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(9267),
                            NextTradingDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(9244),
                            ParentEntity = "XXX",
                            PhoneNumber = "09056570001",
                            PhysicalAddress = "House 59, Ijapo Estate Rd, Akure ",
                            ReportingCurrency = "GBP",
                            ShortName = "Beecee",
                            SuspenseGLAccount = "900GBP500000",
                            SwiftAddress = "XXXYYYZZZ",
                            TradingDate = new DateTime(2020, 5, 19, 0, 9, 40, 845, DateTimeKind.Local).AddTicks(9236)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
